In [3]:
import pandas as pd

In [1]:
#importing the dataset
from google.colab import files
uploaded = files.upload()

Saving cereals.csv to cereals.csv

In [4]:
df = pd.read_csv('cereals.csv')

In [5]:
df

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

In [6]:
df.set_index('name')

                           calories  protein  vitamins     rating
name
100% Bran                        70        4        25  68.402973
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912
Almond Delight                  110        2        25  34.384843
Apple Cinnamon Cheerios         110        2        25  29.509541
Apple Jacks                     110        2        25  33.174094
Basic 4                         130        3        25  37.038562
Bran Chex                        90        2        25  49.120253
Bran Flakes                      90        3        25  53.313813

In [7]:
df

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

In [8]:
df.set_index('name', inplace=True)

In [9]:
df

                           calories  protein  vitamins     rating
name
100% Bran                        70        4        25  68.402973
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912
Almond Delight                  110        2        25  34.384843
Apple Cinnamon Cheerios         110        2        25  29.509541
Apple Jacks                     110        2        25  33.174094
Basic 4                         130        3        25  37.038562
Bran Chex                        90        2        25  49.120253
Bran Flakes                      90        3        25  53.313813

In [11]:
df.head()

                           calories  protein  vitamins     rating
name
100% Bran                        70        4        25  68.402973
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912
Almond Delight                  110        2        25  34.384843

In [12]:
df.head(4)

                           calories  protein  vitamins     rating
name
100% Bran                        70        4        25  68.402973
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912

In [13]:
df.tail()

                         calories  protein  vitamins     rating
name
Apple Cinnamon Cheerios       110        2        25  29.509541
Apple Jacks                   110        2        25  33.174094
Basic 4                       130        3        25  37.038562
Bran Chex                      90        2        25  49.120253
Bran Flakes                    90        3        25  53.313813

In [14]:
df.tail(3)

             calories  protein  vitamins     rating
name
Basic 4           130        3        25  37.038562
Bran Chex          90        2        25  49.120253
Bran Flakes        90        3        25  53.313813

In [15]:
df.describe()

         calories    protein   vitamins     rating
count   10.000000  10.000000  10.000000  10.000000
mean    95.000000   2.900000  22.500000  49.205817
std     25.495098   0.875595   7.905694  20.315297
min     50.000000   2.000000   0.000000  29.509541
25%     75.000000   2.000000  25.000000  34.083970
50%    100.000000   3.000000  25.000000  43.079408
75%    110.000000   3.750000  25.000000  57.897582
max    130.000000   4.000000  25.000000  93.704912

In [16]:
df[1:4]

                           calories  protein  vitamins     rating
name
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912

In [22]:
condition = df['calories']>70
df[condition]

                         calories  protein  vitamins     rating
name
100% Natural Bran             120        3         0  33.983679
Almond Delight                110        2        25  34.384843
Apple Cinnamon Cheerios       110        2        25  29.509541
Apple Jacks                   110        2        25  33.174094
Basic 4                       130        3        25  37.038562
Bran Chex                      90        2        25  49.120253
Bran Flakes                    90        3        25  53.313813

In [23]:
df[(df['calories']>70) & (df['protein']<4)]

                         calories  protein  vitamins     rating
name
100% Natural Bran             120        3         0  33.983679
Almond Delight                110        2        25  34.384843
Apple Cinnamon Cheerios       110        2        25  29.509541
Apple Jacks                   110        2        25  33.174094
Basic 4                       130        3        25  37.038562
Bran Chex                      90        2        25  49.120253
Bran Flakes                    90        3        25  53.313813

In [28]:
df.drop('Basic 4', axis=0, inplace= True)

In [29]:
df

                           calories  protein  vitamins     rating
name
100% Bran                        70        4        25  68.402973
100% Natural Bran               120        3         0  33.983679
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912
Almond Delight                  110        2        25  34.384843
Apple Cinnamon Cheerios         110        2        25  29.509541
Apple Jacks                     110        2        25  33.174094
Bran Chex                        90        2        25  49.120253
Bran Flakes                      90        3        25  53.313813

In [30]:
df.sort_values(by='calories', ascending = False)

                           calories  protein  vitamins     rating
name
100% Natural Bran               120        3         0  33.983679
Almond Delight                  110        2        25  34.384843
Apple Cinnamon Cheerios         110        2        25  29.509541
Apple Jacks                     110        2        25  33.174094
Bran Chex                        90        2        25  49.120253
Bran Flakes                      90        3        25  53.313813
100% Bran                        70        4        25  68.402973
All-Bran                         70        4        25  59.425505
All-Bran with Extra Fiber        50        4        25  93.704912

In [31]:
df.sort_values(by='calories', ascending = True)

                           calories  protein  vitamins     rating
name
All-Bran with Extra Fiber        50        4        25  93.704912
100% Bran                        70        4        25  68.402973
All-Bran                         70        4        25  59.425505
Bran Chex                        90        2        25  49.120253
Bran Flakes                      90        3        25  53.313813
Almond Delight                  110        2        25  34.384843
Apple Cinnamon Cheerios         110        2        25  29.509541
Apple Jacks                     110        2        25  33.174094
100% Natural Bran               120        3         0  33.983679